### PR TITLE
Update freedesktop to 23.06

### PR DESCRIPTION
**Pull request by Laserlicht**

### CODE REVIEW

**Comment by Laserlicht** [comment]
bot, build

**Comment by barthalion** [comment]
bot, build

**Comment by Laserlicht** [comment]
bot, build

**Comment by barthalion** [comment]
@Laserlicht This is not a random build failure. I will trigger a new build when something has changed.

**Comment by Laserlicht** [comment]
Okay, thanks. :)

**Comment by barthalion** [comment]
bot, build

**Comment by barthalion** [comment]
This is good to go, feel welcome to merge it.

**Pull request merged**
